project:
  type: website
  output-dir: docs

website:
  title: "Suparno Bhattacharyya"
  description: "Academic Website - Assistant Research Scientist"
  site-url: "https://suparnobhattacharyya.github.io/"
  repo-url: "https://github.com/suparnobhattacharyya/suparnobhattacharyya.github.io"
  
  
  page-footer:
    background: "#500000"
    foreground: "white"
    # LEFT: Contact Info (Wrapped in div for tight spacing)
    left: |
      <div style="text-align: left; font-size: 1em; line-height: 1.4;">
        <h4>Contact</h4>
        <b>Room No - 224A</b><br>
        <b>Mechanical Engineering Department</b><br>
        <b>IIT(ISM) Dhanbad, Dhanbad, India - 826004</b><br>
        <b>Email: [suparno\@iitism.ac.in](mailto:suparno@iitism.ac.in)</b>
      </div>
    # CENTER: Copyright (Will be centered by CSS)
    center: |
      <span style="font-weight: bold;">Â© 2025. All rights reserved.</span>
    # RIGHT: Visitor Counter + Credit (Stacked and Right Aligned)
    right: |
      <div style="display: flex; flex-direction: column; align-items: flex-end; justify-content: center;">
        <a href="https://www.flagcounter.me/details/gma">
          <img src="https://www.flagcounter.me/gma/" alt="Flag Counter" style="border:0; height: 100px; margin-bottom: 2px;">
        </a><br>
        <br>
        <span style="font-size: 1em; opacity: 1;">Developed by: Amiya Biswas</span>
      </div>
      
      
     
      
      
       
  navbar:
    background: "#500000"   # Texas A&M maroon
    foreground: "white"     # Navbar text color
    collapse: true
    mainfont: "Adobe Garamond"
    logo: images/ISM_logo.png
    logo-href: "https://suparnobhattacharyya.github.io/cv.html"  # Logo redirects CV
    title: "Suparno Bhattacharyya"
    title-href: index.qmd  # Text redirects to Home
 
    left:
      - href: home.qmd
        text: "Home"
      - href: publications.qmd
        text: "Publications"
      - href: projects.qmd
        text: "Research"
      - href: teachings.qmd
        text: "Teaching"
      - href: collaborators.qmd
        text: "Collaborators"
      - text: "Others"
        menu: 
          - text: "Media"
            href: media.qmd
          - text: "News"
            href: news.qmd
          - text: "Resources"
            href: resources.qmd
          - text: "Webinar"
            href: Webinar.qmd
      - href: opportunities.qmd
        text: "Opportunities"
      - href: cv.qmd
        text: "CV"

    right:
      - icon: linkedin
        href: "https://linkedin.com/in/suparnob/"
        aria-label: LinkedIn
      - icon: github
        href: "https://github.com/SUPARNOBHATTACHARYYA"
        aria-label: GitHub
      - icon: envelope
        href: "mailto:suparno@iitism.ac.in"
        aria-label: Email
      - icon: magnifying-glass
        aria-label: Search

  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    
    toc: true
    toc-location: right
    page-layout: article
    link-external-newwindow: true
    theme-toggle: true
    ##mainfont: "Lora"
    ##heading-font: "Playfair Display"

execute:
  freeze: auto

editor: visual
