project:
  type: website
  output-dir: docs

website:
  title: "Suparno Bhattacharyya"
  description: "Academic Website - Assistant Research Scientist"
  site-url: "https://suparnobhattacharyya.github.io/"
  repo-url: "https://github.com/suparnobhattacharyya/suparnobhattacharyya.github.io"
  
  page-footer:
    left: "Â© 2025. All rights reserved."
    right: |
      <a href="https://www.hitwebcounter.com/" target="_blank">
      <img src="https://hitwebcounter.com/counter/counter.php?page=21454414&style=0006&nbdigits=6&type=page&initCount=0" title="Free Tools" Alt="Free Tools" border="0" /></a>
    
  navbar:
    background: "#500000"   # Texas A&M maroon
    foreground: "white"     # Navbar text color
    collapse: true
    mainfont: "Adobe Garamond"
    logo: images/ISM_logo.png
    logo-href: "https://www.iitism.ac.in"  # Logo redirects to IIT ISM site
    title: "Suparno Bhattacharyya"
    title-href: index.qmd  # Text redirects to Home
 
    left:
      - href: home.qmd
        text: "Home"
      - href: publications.qmd
        text: "Publications"
      - href: projects.qmd
        text: "Research"
      - href: teachings.qmd
        text: "Teaching"
      - href: collaborators.qmd
        text: "Collaborators"
      - href: media.qmd
        text: "Media"
      - href: news.qmd
        text: "News"
      - href: opportunities.qmd
        text: "Opportunities"
      - href: cv.qmd
        text: "CV"

    right:
      - icon: linkedin
        href: "https://linkedin.com/in/suparnob/"
        aria-label: LinkedIn
      - icon: github
        href: "https://github.com/SUPARNOBHATTACHARYYA"
        aria-label: GitHub
      - icon: envelope
        href: "mailto:suparno@iitism.ac.in"
        aria-label: Email
      - icon: magnifying-glass
        aria-label: Search

  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    
    toc: true
    toc-location: right
    page-layout: article
    link-external-newwindow: true
    theme-toggle: true
    ##mainfont: "Lora"
    ##heading-font: "Playfair Display"

execute:
  freeze: auto

editor: visual
